import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import MainLayout from "@/components/layout/MainLayout";
import { Toaster } from "sonner";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Equinox Test App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <MainLayout>
            {children}
            <Toaster position="top-center"/>
          </MainLayout>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
